# Generated by Django 5.2.9 on 2026-01-03 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLexicalStats',
            fields=[
                ('lemma_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('wrong', models.PositiveIntegerField(default=0)),
                ('difficulty_score', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'global_lexical_stats',
                'indexes': [models.Index(fields=['difficulty_score'], name='global_lexi_difficu_07224a_idx'), models.Index(fields=['updated_at'], name='global_lexi_updated_f999b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LexicalDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma_id', models.CharField(db_index=True, max_length=50)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('wrong', models.PositiveIntegerField(default=0)),
                ('near_miss_count', models.PositiveIntegerField(default=0)),
                ('confusable_errors', models.PositiveIntegerField(default=0)),
                ('difficulty_score', models.FloatField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexical_difficulties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lexical_difficulty',
                'indexes': [models.Index(fields=['user', 'lemma_id'], name='lexical_dif_user_id_d9eae2_idx'), models.Index(fields=['difficulty_score'], name='lexical_dif_difficu_4c13d3_idx'), models.Index(fields=['last_seen_at'], name='lexical_dif_last_se_53da4c_idx')],
                'unique_together': {('user', 'lemma_id')},
            },
        ),
    ]
