# Generated by Django 5.2.9 on 2025-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('google', 'Google')], help_text='Authentication provider', max_length=50, null=True),
        ),
    ]
